package api_test

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/d31ma/heimdall/internal/api"
	"github.com/d31ma/heimdall/internal/auth"
)

// pathValueRequest fabricates a request carrying the path values a route's
// resolver reads, without needing a live server.
func pathValueRequest(pattern string) *http.Request {
	request := httptest.NewRequest(http.MethodGet, "/", nil)
	for _, segment := range strings.Split(pattern, "/") {
		name, ok := strings.CutPrefix(segment, "{")
		if !ok {
			continue
		}
		name = strings.TrimSuffix(name, "}")
		request.SetPathValue(name, "sample")
	}
	return request
}

// TestEveryRouteNamesExactlyOneKnownAction is the mechanical half of the plan's
// "every route in the table maps to exactly one action". The other half — that
// the mapping is the *right* one — is a review question, not a test question.
func TestEveryRouteNamesExactlyOneKnownAction(t *testing.T) {
	server := &api.Server{Version: "test"}
	seen := map[string]bool{}

	for _, route := range server.Routes() {
		key := route.Method + " " + route.Pattern
		t.Run(key, func(t *testing.T) {
			if seen[key] {
				t.Fatalf("%s is registered twice; the second registration would panic on the mux", key)
			}
			seen[key] = true

			if !route.Action.Valid() {
				t.Fatalf("names action %q, which is outside the closed vocabulary", route.Action)
			}
			if route.Resource == nil {
				t.Fatal("has no resource resolver, so it could not be authorized")
			}
			if route.Handler == nil {
				t.Fatal("has no handler")
			}

			resource, err := route.Resource(pathValueRequest(route.Pattern))
			if err != nil {
				t.Fatalf("resource resolver failed on well-formed path values: %v", err)
			}
			if resource == "" {
				t.Fatal("resource resolver produced an empty resource")
			}
		})
	}
}

// TestMutatingRoutesAreNeverRead catches the copy-paste that matters most: a
// new POST route inheriting the read action of the GET it was pasted from.
func TestMutatingRoutesAreNeverRead(t *testing.T) {
	readOnly := map[auth.Action]bool{
		auth.AppRead: true, auth.TargetRead: true, auth.RepoRead: true,
		auth.ProjectRead: true, auth.AuditRead: true,
		auth.ObserveMetrics: true, auth.ObserveLogs: true, auth.ObserveEvents: true,
	}
	for _, route := range (&api.Server{}).Routes() {
		switch route.Method {
		case http.MethodGet, http.MethodHead:
			continue
		}
		if readOnly[route.Action] {
			t.Errorf("%s %s mutates but is authorized with the read action %q",
				route.Method, route.Pattern, route.Action)
		}
	}
}

// TestUnauthenticatedSurfaceIsExactlyThree pins the routes that skip the
// boundary. Adding a fourth must be a deliberate edit to this test.
func TestUnauthenticatedSurfaceIsExactlyThree(t *testing.T) {
	handler := (&api.Server{Version: "test"}).Handler()

	for _, path := range []string{"/healthz", "/api/v1/version"} {
		recorder := httptest.NewRecorder()
		handler.ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, path, nil))
		if recorder.Code != http.StatusOK {
			t.Errorf("%s = %d, want 200", path, recorder.Code)
		}
	}

	// /readyz is the third, and with no engine configured it must report the
	// control plane as not ready rather than as healthy.
	recorder := httptest.NewRecorder()
	handler.ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/readyz", nil))
	if recorder.Code != http.StatusServiceUnavailable {
		t.Errorf("/readyz with no engine = %d, want 503", recorder.Code)
	}

	// Every table route must refuse without an engine, never fall through.
	for _, route := range (&api.Server{Version: "test"}).Routes() {
		recorder := httptest.NewRecorder()
		request := httptest.NewRequest(route.Method, strings.NewReplacer("{project}", "alpha", "{app}", "checkout").Replace(route.Pattern), nil)
		handler.ServeHTTP(recorder, request)
		if recorder.Code != http.StatusServiceUnavailable {
			t.Errorf("%s %s with no engine = %d, want 503", route.Method, route.Pattern, recorder.Code)
		}
	}
}

// TestContractMatchesTheRouteTable keeps api/openapi.json honest. The contract
// is generated output; a hand-edit or a new route without a regeneration is a
// published lie about what the server does.
func TestContractMatchesTheRouteTable(t *testing.T) {
	// The contract carries the release version, so it is regenerated by the
	// same bump that edits VERSION rather than drifting a release behind.
	generated, err := api.OpenAPI(repoVersion(t))
	if err != nil {
		t.Fatalf("generate contract: %v", err)
	}
	committed, err := os.ReadFile(filepath.Join("..", "..", api.ContractPath))
	if err != nil {
		t.Fatalf("read committed contract: %v", err)
	}
	if !bytes.Equal(generated, committed) {
		t.Fatalf("%s is stale; regenerate it with:\n\n\theimdall contract --write %s\n",
			api.ContractPath, api.ContractPath)
	}
}

// TestContractDescribesEveryAuthorizedRoute proves the generator did not
// quietly drop one.
func TestContractDescribesEveryAuthorizedRoute(t *testing.T) {
	generated, err := api.OpenAPI(repoVersion(t))
	if err != nil {
		t.Fatalf("generate contract: %v", err)
	}
	var document struct {
		Paths map[string]map[string]struct {
			Action string `json:"x-heimdall-action"`
		} `json:"paths"`
	}
	if err := json.Unmarshal(generated, &document); err != nil {
		t.Fatalf("decode contract: %v", err)
	}
	for _, route := range (&api.Server{}).Routes() {
		operation, ok := document.Paths[route.Pattern][strings.ToLower(route.Method)]
		if !ok {
			t.Errorf("%s %s is missing from the contract", route.Method, route.Pattern)
			continue
		}
		if operation.Action != route.Action.String() {
			t.Errorf("%s %s documents action %q, route uses %q",
				route.Method, route.Pattern, operation.Action, route.Action)
		}
	}
}

// repoVersion reads the VERSION file the release build stamps into the binary.
func repoVersion(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "VERSION"))
	if err != nil {
		t.Fatalf("read VERSION: %v", err)
	}
	return strings.TrimSpace(string(raw))
}
